Add Ryan's aboutus and PPP
AY2122S2-CS2103-W16-1/tp pull request #11
Opened 2022-02-27 12:38 UTC by ryanwalterlee

2022-02-27 14:39 UTC, benmurphyy commented
@ryanwalterlee need to add your part of the user guide too

2022-02-28 03:11 UTC, yokester98 requested changes
Need to change that one portion in AboutUs to your full name!

2022-02-28 03:11 UTC, yokester98 commented on docs/AboutUs.md
>  ### Jean Doe
Need to change this to your full name

2022-02-28 03:22 UTC, ryanwalterlee commented
The user guide part, I only did the image, which is already there. I however changed the other image to suit our app. Let me know if there's any part I missed.

2022-02-28 03:47 UTC, benmurphyy requested changes
remove the bin folder items

2022-02-28 05:14 UTC, benmurphyy requested changes
one more part in user guide to change
![Screenshot 2022-02-28 at 1 13 51 PM](https://user-images.githubusercontent.com/47269122/155927900-d2bfeea6-af8a-4245-b88c-0113a5801811.png)

2022-02-28 07:31 UTC, benmurphyy requested changes
for help part, the url for our user guide is
https://ay2122s2-cs2103-w16-1.github.io/tp/UserGuide.html

2022-02-28 11:58 UTC, benmurphyy approved these changes

2022-02-28 12:05 UTC, merged