Fix Edit Command
AY2122S2-CS2103-W16-1/tp pull request #48
Opened 2022-03-14 17:53 UTC by sophiien

- Checking of person subtypes is now done using instanceof 
- User cannot edit person / module if not on respective module viewing page

2022-03-15 03:42 UTC, benmurphyy requested changes
## Bugs Found
- when i type in certain incomplete commands, like `edit 1`, and press enter, nothing happens, no message is shown to me. I can only see in the terminal that there was a nosuchelementexception thrown. Please make sure all possible erroneous inputs will display some message to the user informing them of the problem.
<img width="452" alt="Screenshot 2022-03-15 at 11 34 54 AM" src="https://user-images.githubusercontent.com/47269122/158301680-046ac258-88b1-489c-9e33-f577dde65c39.png">

- i can type any `edit 1 o/<gibberish>` on the person page, instead of telling me that thats invalid, it tells me to switch view to module. Probably because of an if-else block used in your parsing that has too large a scope.
- adding a new module to a person dosen't work at all, like `edit 1 o/person nm/cs2103`, nothing happens when i press enter. instead this error is showing in terminal.
<img width="500" alt="Screenshot 2022-03-15 at 11 39 22 AM" src="https://user-images.githubusercontent.com/47269122/158301654-6373cd22-1c77-4dd6-b1e6-597cb83ac947.png">

### note regarding your update to this pr - please include the commands and how to use them in pr description for easy debugging, or update the user guide to contain them. Make sure that each work before updating this pr

2022-03-15 08:44 UTC, geraldneo567 requested changes
You need to throw either a `CommandException` or a `ParseException` depending on whether you are in `EditCommand::execute()` or `EditCommandParser`, so that when the user enters wrong input (e.g input that is missing required information or has the wrong formatting, i.e when `!(argMultimap.getValue(PREFIX_XXXX).isPresent()))` you should throw an exception instead of just continuing execution. This will cause the user to be prompted and see what's wrong on the GUI.

2022-03-15 10:24 UTC, sophiien commented
****Usage of edit command (updated in UG too) 

- edit INDEX o/OPTION [n/NAME or MODULENAME] [p/PHONE] ...
- e.g. edit 1 o/person nm/CS2103 : adds CS2103 to list of person's modules 

The following incorrect commands will result in an error message shown in the console:
- Missing compulsory fields i.e. INDEX or OPTION 
- Invalid module code 
- Editing person/module when not in correct viewing page 
- Less than 1 field provided to be edited

2022-03-15 12:01 UTC, benmurphyy requested changes
Seems to be working, good job!
Just clean up user guide and the test case thats failing, and we can merge!

2022-03-15 12:01 UTC, benmurphyy commented on docs/UserGuide.md
>      * `module`: Edits the module specified by compulsory field `m/MODULE`. Optional fields `[n/NAME] [nm/NEWMODULE]` to specify the new name or module code of the module.
I think you wrote the wrong fields here, this should be for person, not module

2022-03-15 16:31 UTC, benmurphyy requested changes

2022-03-15 16:31 UTC, benmurphyy commented on docs/UserGuide.md
>      * `module`: Edits the module specified by compulsory field `m/MODULE`. Optional fields `[n/NAME] [nm/NEWMODULE]` to specify the new name or module code of the module.
this part of the user guide is still not fixed in this pr

2022-03-16 06:09 UTC, yokester98 requested changes
Well done! I did notice a portion of the code that may be redundant though (but I might be wrong!) Take a look and let me know what you think?

2022-03-16 06:09 UTC, yokester98 commented on src/main/java/unibook/logic/commands/EditCommand.java
> +                    person.setModules(moduleSet);
I feel that this line
`person.setModules(moduleSet)`
is redundant actually, as the person's moduleSet is already beinng modified in the lines above. If my understanding is correct, the person's moduleSet will still be updated without needing this line. What do you think? 🤔

2022-03-16 13:17 UTC, geraldneo567 approved these changes
LGTM!

2022-03-16 13:22 UTC, yokester98 approved these changes

2022-03-16 13:50 UTC, benmurphyy approved these changes

2022-03-16 13:51 UTC, merged