Enhanced edit functionalities for group and key events
AY2122S2-CS2103-W16-1/tp pull request #97
Opened 2022-03-28 05:28 UTC by sophiien

**Eding Groups**

- To edit fields of a group, user must be in the module page. If not, there will be an error shown on the console to tell users to switch to the module page. 
- Format for editing groups: `edit INDEX o/group m/MODULE_CODE [g/NEW_GROUP_NAME] [mt/INDEX NEW_MEETING_TIME]`.  
- `INDEX` refers to the index of the group on the list of groups stated by the `m/MODULE_CODE`. The `INDEX` in `mt/` refers to the index of the meeting time to be edited. `INDEX`, `o/group` and `m/MODULE_CODE` are compulsory fields, and an error will be shown if either of these are missing. 
- [TODO] Editing person to add to a group function still not available, waiting for UI changes. 

**Editing Key Events**
- To edit fields of a key event, user must be in the module page. If not, there will be an error shown on the console to tell users to switch to the module page 
- Format for editing key events: `edit INDEX o/keyevent ke/INDEX [dt/DATETIME] [ty/TYPE]`. 
-  `INDEX` refers to the index of the module on the list of modules shown on the modules page. The `INDEX` in `ke/` refers to the index of the key event to be edited. `INDEX`, `o/keyevent` and `ke/INDEX` are compulsory fields, and an error will be shown if either of these are missing.

2022-03-28 06:34 UTC, benmurphyy requested changes
## Features missing, not following the standardised format set earlier.

- Refer to the shared document and follow the command format there. Implement missing commands.

2022-03-28 16:36 UTC, sophiien commented
**Editing Groups**

- To edit fields of a group, user must be in the module or groups page. If not, there will be an error shown on the console to tell users to switch to the module / groups page.
- Format for editing groups: edit INDEX o/group m/MODULE_CODE [g/NEW_GROUP_NAME] [mt/INDEX NEW_MEETING_TIME].
- INDEX refers to the index of the group on the list of groups stated by the m/MODULE_CODE. The INDEX in mt/ refers to the index of the meeting time to be edited. INDEX, o/group and m/MODULE_CODE are compulsory fields, and an error will be shown if either of these are missing.
<img width="1065" alt="Screenshot 2022-03-29 at 12 23 19 AM" src="https://user-images.githubusercontent.com/77224606/160443313-eec5a8a0-eac1-45e6-8031-1e8ff82b7e8b.png">


**Adding existing person to an existing group** 

- Format for editing person : edit INDEX o/person m/MODULE_CODE g/NEW_GROUP_NAME
- If any of the compulsory fields are missing, user will prompt them to use the correct format 
<img width="1078" alt="Screenshot 2022-03-29 at 12 16 01 AM" src="https://user-images.githubusercontent.com/77224606/160442104-ec998ca8-9a97-4e74-9373-f1018a260dab.png">
- If person at `INDEX` is a professor, will show an error that can only add students to a group 
<img width="1079" alt="Screenshot 2022-03-29 at 12 16 49 AM" src="https://user-images.githubusercontent.com/77224606/160442249-4427ffac-917c-4c99-b57e-a92ea01a5817.png">
- If person at `INDEX` is not a student stated by `m/MODULE_CODE`, will show error to first add the student before adding to group. 
<img width="1076" alt="Screenshot 2022-03-29 at 12 17 48 AM" src="https://user-images.githubusercontent.com/77224606/160442397-a5427419-b942-425b-8e14-bf2bbc3a2153.png">
- If person at `INDEX` already exists in the group, will show error that person is already in the group.
<img width="1066" alt="Screenshot 2022-03-29 at 12 18 34 AM" src="https://user-images.githubusercontent.com/77224606/160442540-744647ee-63bc-4393-aca7-b5fa817ef8bf.png">


**Editing Key Events**

- To edit fields of a key event, user must be in the module page. If not, there will be an error shown on the console to tell users to switch to the module page
<img width="1063" alt="Screenshot 2022-03-29 at 12 34 16 AM" src="https://user-images.githubusercontent.com/77224606/160445216-aea219a3-8f72-408c-8fe4-bf9adf4cc2d9.png">

- Format for editing key events: edit INDEX o/keyevent ke/INDEX [dt/DATETIME] [type/TYPE].
- INDEX refers to the index of the module on the list of modules shown on the modules page. The INDEX in ke/ refers to the index of the key event to be edited. INDEX, o/keyevent and ke/INDEX are compulsory fields, and an error will be shown if either of these are missing.

2022-03-29 03:24 UTC, benmurphyy requested changes
## Missing features and wrong error messages
<img width="1091" alt="Screenshot 2022-03-29 at 11 18 42 AM" src="https://user-images.githubusercontent.com/47269122/160526384-272b4cf3-a865-455d-9d96-5274f20f0c61.png">
<img width="1118" alt="Screenshot 2022-03-29 at 11 20 44 AM" src="https://user-images.githubusercontent.com/47269122/160526539-b27823ce-8b2c-4d29-ace3-31f40c025bee.png">

- remove o/ tag from command edits to maintain **app cohesion**

## Please follow documentation laid out to maintain app cohesion

2022-03-29 03:38 UTC, benmurphyy requested changes
## Follow documentation standardised format
- Confirm all the commands as stipulated in the document work before updating this PR.

2022-03-29 03:40 UTC, geraldneo567 requested changes

2022-03-29 03:40 UTC, geraldneo567 commented on src/main/java/unibook/logic/commands/EditCommand.java
One way to handle the lack of `option` is to have an enum type here, similar to what I have pasted in the screenshot.
![image](https://user-images.githubusercontent.com/83899964/160528338-a265db1d-e5c5-4d27-a1a3-934bce1ee385.png)


Then when you create a command in `EditCommandParser`, you can pass in the respective type (removes the need for all the boolean checks, etc cos you know that the respective fields you need will not be null when you create a command with the specific enum. To handle different behaviour across different views, the `execute` method has booleans to show which group list is showing.

![image](https://user-images.githubusercontent.com/83899964/160528518-f89e082e-e189-4a1b-9bf2-fd43b63bd6ef.png)


This is an example - see case `module` which is the same command that behaves differently on differnet pages.

2022-03-29 12:40 UTC, benmurphyy requested changes
- change the message shown when adding person to group or module to something like "added XX to group YYY" not this generic message
<img width="844" alt="Screenshot 2022-03-29 at 8 27 29 PM" src="https://user-images.githubusercontent.com/47269122/160611079-ba9f76e5-0e5f-4a59-b0d3-c6adf308e06f.png">

- unable to edit office of professor
<img width="511" alt="Screenshot 2022-03-29 at 8 31 52 PM" src="https://user-images.githubusercontent.com/47269122/160611840-3c0a0084-5679-4b1d-92b5-be32cbe727c5.png">

2022-03-29 12:40 UTC, benmurphyy commented on docs/UserGuide.md
> +Format: `edit INDEX o/group m/MODULE [g/GROUPNAME] [mt/INDEX DATETIME]`
groupname is a compulsory field

2022-03-29 16:42 UTC, sophiien commented
Fixed bug identified by @geraldneo567 in previous comment.

2022-03-30 07:24 UTC, geraldneo567 approved these changes

2022-03-30 08:23 UTC, benmurphyy approved these changes
LGTM

2022-03-30 08:50 UTC, merged